### ISSUE TITLE
Firmware version 1.8 vs Special edition?

### ISSUE THREAD

**Issue by andr229k** [ajxs/yamaha_dx97#2] opened 2023-08-18 23:56 UTC
There is mentioned on the  main page that this firmware lent sources from 1.8.

I think Yamaha adressed some of the issues with 1.8 with their Special edition firmware,

[SER7.zip](https://github.com/ajxs/yamaha_dx97/files/12384502/SER7.zip)

Would this be helpful for the project?

More info here:
https://faq.yamaha.com/usa/s/article/U0002040

**Comment by ajxs** [comment] 2023-08-19 00:22
Hello! That's correct. Some of the code was originally borrowed from the DX7 v1.8 firmware.
If I understand things correctly, the SER-7 ROM was intended to introduce new functionality, rather than fix bugs. I'm pretty sure that the code this ROM borrowed from the V1.8 firmware would be the same in the SER-7 ROM. I can't find a list of any bugs it fixed online. I'll keep looking and see if there's anything I can learn from it.
With regards to that new functionality, the DX9 has a lot less RAM. It's already near the very limit of what it can support. Maybe in the future I could add the code to show the master tune setting. I've got some basic code in there to support changing the MIDI output channel. I never got a chance to finish it though. Maybe I can do this sometime in the future.

**Closed** 2023-09-05 23:12 UTC
